// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Home",
    "link": "/"
  },
  {
    "text": "Features",
    "link": "/features"
  },
  {
    "text": "Getting started",
    "link": "/getting-started",
    "items": [
      {
        "text": "Download",
        "link": "/getting-started#download"
      },
      {
        "text": "Install on Windows",
        "link": "/getting-started#install-on-windows"
      },
      {
        "text": "Install on macOS",
        "link": "/getting-started#install-on-macos"
      },
      {
        "text": "Install on Linux",
        "link": "/getting-started#install-on-linux"
      },
      {
        "text": "What's next",
        "link": "/getting-started#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Settings",
    "link": "/settings",
    "items": [
      {
        "text": "General",
        "link": "/settings#general"
      },
      {
        "text": "Shortcuts",
        "link": "/settings#shortcuts"
      },
      {
        "text": "Proxy",
        "link": "/settings#proxy"
      },
      {
        "text": "Databases",
        "link": "/settings#databases"
      },
      {
        "text": "AI",
        "link": "/settings#ai"
      },
      {
        "text": "What's next",
        "link": "/settings#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "AI assistant",
    "link": "/ai",
    "items": [
      {
        "text": "API keys",
        "link": "/ai#api-keys"
      },
      {
        "text": "Opening the AI sidebar",
        "link": "/ai#opening-the-ai-sidebar"
      },
      {
        "text": "Using chat",
        "link": "/ai#using-chat"
      },
      {
        "text": "What the assistant can do",
        "link": "/ai#what-the-assistant-can-do"
      },
      {
        "text": "What's next",
        "link": "/ai#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Team hubs",
    "link": "/team-hubs",
    "items": [
      {
        "text": "Prerequisites",
        "link": "/team-hubs#prerequisites"
      },
      {
        "text": "Managing team hubs",
        "link": "/team-hubs#managing-team-hubs"
      },
      {
        "text": "Admin tokens",
        "link": "/team-hubs#admin-tokens"
      },
      {
        "text": "Managing team users",
        "link": "/team-hubs#managing-team-users"
      },
      {
        "text": "Collections on a team hub",
        "link": "/team-hubs#collections-on-a-team-hub"
      },
      {
        "text": "Moving and deleting collections",
        "link": "/team-hubs#moving-and-deleting-collections"
      },
      {
        "text": "Team hubs vs other sharing options",
        "link": "/team-hubs#team-hubs-vs-other-sharing-options"
      },
      {
        "text": "Team Hub LLM access",
        "link": "/team-hubs#team-hub-llm-access"
      },
      {
        "text": "Limitations",
        "link": "/team-hubs#limitations"
      },
      {
        "text": "What's next",
        "link": "/team-hubs#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Certificates",
    "link": "/certificates",
    "items": [
      {
        "text": "My identity",
        "link": "/certificates#my-identity"
      },
      {
        "text": "Exporting your public key",
        "link": "/certificates#exporting-your-public-key"
      },
      {
        "text": "Exporting and importing your key pair",
        "link": "/certificates#exporting-and-importing-your-key-pair"
      },
      {
        "text": "Trusted keys",
        "link": "/certificates#trusted-keys"
      },
      {
        "text": "Working with collaborators",
        "link": "/certificates#working-with-collaborators"
      },
      {
        "text": "Security notes",
        "link": "/certificates#security-notes"
      },
      {
        "text": "What's next",
        "link": "/certificates#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Collections",
    "link": "/collections",
    "items": [
      {
        "text": "Sidebar guide",
        "link": "/collections#sidebar-guide"
      },
      {
        "text": "Creating collections",
        "link": "/collections#creating-collections"
      },
      {
        "text": "Renaming and deleting",
        "link": "/collections#renaming-and-deleting"
      },
      {
        "text": "Collection Settings",
        "link": "/collections#collection-settings"
      },
      {
        "text": "Working with saved requests",
        "link": "/collections#working-with-saved-requests"
      },
      {
        "text": "Import and export",
        "link": "/collections#import-and-export"
      },
      {
        "text": "Sharing collections",
        "link": "/collections#sharing-collections"
      },
      {
        "text": "How collections affect sends",
        "link": "/collections#how-collections-affect-sends"
      },
      {
        "text": "Storage and backup",
        "link": "/collections#storage-and-backup"
      },
      {
        "text": "Keyboard shortcuts",
        "link": "/collections#keyboard-shortcuts"
      },
      {
        "text": "What's next",
        "link": "/collections#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Making requests",
    "link": "/requests",
    "items": [
      {
        "text": "The request editor",
        "link": "/requests#the-request-editor"
      },
      {
        "text": "Query parameters",
        "link": "/requests#query-parameters"
      },
      {
        "text": "Headers",
        "link": "/requests#headers"
      },
      {
        "text": "Authorization",
        "link": "/requests#authorization"
      },
      {
        "text": "Request body",
        "link": "/requests#request-body"
      },
      {
        "text": "Variables in requests",
        "link": "/requests#variables-in-requests"
      },
      {
        "text": "Collection context",
        "link": "/requests#collection-context"
      },
      {
        "text": "Scripts at a glance",
        "link": "/requests#scripts-at-a-glance"
      },
      {
        "text": "Sending a request",
        "link": "/requests#sending-a-request"
      },
      {
        "text": "Reading the response",
        "link": "/requests#reading-the-response"
      },
      {
        "text": "Console",
        "link": "/requests#console"
      },
      {
        "text": "Tabs, collections, and saving",
        "link": "/requests#tabs-collections-and-saving"
      },
      {
        "text": "Keyboard shortcuts",
        "link": "/requests#keyboard-shortcuts"
      },
      {
        "text": "Limitations",
        "link": "/requests#limitations"
      },
      {
        "text": "What's next",
        "link": "/requests#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Request scripts",
    "link": "/request-scripts",
    "items": [
      {
        "text": "Execution order",
        "link": "/request-scripts#execution-order"
      },
      {
        "text": "The hc object",
        "link": "/request-scripts#the-hc-object"
      },
      {
        "text": "console",
        "link": "/request-scripts#console"
      },
      {
        "text": "What gets applied back",
        "link": "/request-scripts#what-gets-applied-back"
      },
      {
        "text": "Sandbox limits",
        "link": "/request-scripts#sandbox-limits"
      },
      {
        "text": "Examples",
        "link": "/request-scripts#examples"
      },
      {
        "text": "Migrating from Postman",
        "link": "/request-scripts#migrating-from-postman"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Testing",
    "link": "/testing",
    "items": [
      {
        "text": "Where tests run",
        "link": "/testing#where-tests-run"
      },
      {
        "text": "Writing a test",
        "link": "/testing#writing-a-test"
      },
      {
        "text": "Assertions",
        "link": "/testing#assertions"
      },
      {
        "text": "Reading results",
        "link": "/testing#reading-results"
      },
      {
        "text": "Common patterns",
        "link": "/testing#common-patterns"
      },
      {
        "text": "Tips and limits",
        "link": "/testing#tips-and-limits"
      },
      {
        "text": "What's next",
        "link": "/testing#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Environments",
    "link": "/environments",
    "items": [
      {
        "text": "Managing environments",
        "link": "/environments#managing-environments"
      },
      {
        "text": "Selecting an environment",
        "link": "/environments#selecting-an-environment"
      },
      {
        "text": "Variables",
        "link": "/environments#variables"
      },
      {
        "text": "Precedence",
        "link": "/environments#precedence"
      },
      {
        "text": "Storage",
        "link": "/environments#storage"
      },
      {
        "text": "Export and import",
        "link": "/environments#export-and-import"
      }
    ],
    "collapsed": false
  }
]
