// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Home",
    "link": "/"
  },
  {
    "text": "Getting started",
    "link": "/getting-started"
  },
  {
    "text": "Features",
    "link": "/features"
  },
  {
    "text": "Prerequisites",
    "link": "/prerequisites"
  },
  {
    "text": "Scripts",
    "link": "/scripts"
  },
  {
    "text": "Request scripts",
    "link": "/request-scripts",
    "items": [
      {
        "text": "Execution order",
        "link": "/request-scripts#execution-order"
      },
      {
        "text": "The hc object",
        "link": "/request-scripts#the-hc-object"
      },
      {
        "text": "console",
        "link": "/request-scripts#console"
      },
      {
        "text": "What gets applied back",
        "link": "/request-scripts#what-gets-applied-back"
      },
      {
        "text": "Sandbox limits",
        "link": "/request-scripts#sandbox-limits"
      },
      {
        "text": "Examples",
        "link": "/request-scripts#examples"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Project structure",
    "link": "/project-structure"
  },
  {
    "text": "Tech stack",
    "link": "/tech-stack"
  },
  {
    "text": "Data",
    "link": "/data"
  },
  {
    "text": "License",
    "link": "/license"
  }
]
