// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Home",
    "link": "/"
  },
  {
    "text": "Features",
    "link": "/features"
  },
  {
    "text": "Getting started",
    "link": "/getting-started",
    "items": [
      {
        "text": "Download",
        "link": "/getting-started#download"
      },
      {
        "text": "Install on Windows",
        "link": "/getting-started#install-on-windows"
      },
      {
        "text": "Install on macOS",
        "link": "/getting-started#install-on-macos"
      },
      {
        "text": "Install on Linux",
        "link": "/getting-started#install-on-linux"
      },
      {
        "text": "What's next",
        "link": "/getting-started#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Settings",
    "link": "/settings",
    "items": [
      {
        "text": "General",
        "link": "/settings#general"
      },
      {
        "text": "SQLite",
        "link": "/settings#sqlite"
      },
      {
        "text": "Firestore",
        "link": "/settings#firestore"
      },
      {
        "text": "MySQL",
        "link": "/settings#mysql"
      },
      {
        "text": "PostgreSQL",
        "link": "/settings#postgresql"
      },
      {
        "text": "What's next",
        "link": "/settings#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Collections",
    "link": "/collections",
    "items": [
      {
        "text": "Sidebar guide",
        "link": "/collections#sidebar-guide"
      },
      {
        "text": "Creating collections",
        "link": "/collections#creating-collections"
      },
      {
        "text": "Renaming and deleting",
        "link": "/collections#renaming-and-deleting"
      },
      {
        "text": "Collection Settings",
        "link": "/collections#collection-settings"
      },
      {
        "text": "Working with saved requests",
        "link": "/collections#working-with-saved-requests"
      },
      {
        "text": "Import and export",
        "link": "/collections#import-and-export"
      },
      {
        "text": "How collections affect sends",
        "link": "/collections#how-collections-affect-sends"
      },
      {
        "text": "Storage and backup",
        "link": "/collections#storage-and-backup"
      },
      {
        "text": "Keyboard shortcuts",
        "link": "/collections#keyboard-shortcuts"
      },
      {
        "text": "Limitations",
        "link": "/collections#limitations"
      },
      {
        "text": "What's next",
        "link": "/collections#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Making requests",
    "link": "/requests",
    "items": [
      {
        "text": "The request editor",
        "link": "/requests#the-request-editor"
      },
      {
        "text": "Query parameters",
        "link": "/requests#query-parameters"
      },
      {
        "text": "Headers",
        "link": "/requests#headers"
      },
      {
        "text": "Request body",
        "link": "/requests#request-body"
      },
      {
        "text": "Variables in requests",
        "link": "/requests#variables-in-requests"
      },
      {
        "text": "Collection context",
        "link": "/requests#collection-context"
      },
      {
        "text": "Scripts at a glance",
        "link": "/requests#scripts-at-a-glance"
      },
      {
        "text": "Sending a request",
        "link": "/requests#sending-a-request"
      },
      {
        "text": "Reading the response",
        "link": "/requests#reading-the-response"
      },
      {
        "text": "Console",
        "link": "/requests#console"
      },
      {
        "text": "Tabs, collections, and saving",
        "link": "/requests#tabs-collections-and-saving"
      },
      {
        "text": "Authentication",
        "link": "/requests#authentication"
      },
      {
        "text": "Keyboard shortcuts",
        "link": "/requests#keyboard-shortcuts"
      },
      {
        "text": "Limitations",
        "link": "/requests#limitations"
      },
      {
        "text": "What's next",
        "link": "/requests#whats-next"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Request scripts",
    "link": "/request-scripts",
    "items": [
      {
        "text": "Execution order",
        "link": "/request-scripts#execution-order"
      },
      {
        "text": "The hc object",
        "link": "/request-scripts#the-hc-object"
      },
      {
        "text": "console",
        "link": "/request-scripts#console"
      },
      {
        "text": "What gets applied back",
        "link": "/request-scripts#what-gets-applied-back"
      },
      {
        "text": "Sandbox limits",
        "link": "/request-scripts#sandbox-limits"
      },
      {
        "text": "Examples",
        "link": "/request-scripts#examples"
      }
    ],
    "collapsed": false
  },
  {
    "text": "Environments",
    "link": "/environments",
    "items": [
      {
        "text": "Managing environments",
        "link": "/environments#managing-environments"
      },
      {
        "text": "Selecting an environment",
        "link": "/environments#selecting-an-environment"
      },
      {
        "text": "Variables",
        "link": "/environments#variables"
      },
      {
        "text": "Precedence",
        "link": "/environments#precedence"
      },
      {
        "text": "Storage",
        "link": "/environments#storage"
      }
    ],
    "collapsed": false
  }
]
