/**
 * Ordered VitePress sidebar manifest for canonical docs pages.
 *
 * Generated by scripts/split-readme.mjs. Edit to reorder nav or add pages.
 * Run `pnpm docs:build:nav` to regenerate the sidebar.
 */

/** @typedef {{ name: string; source: string; title: string; targetDir?: string }} SyncedDocPage */

/** @type {SyncedDocPage[]} Optional synced pages copied from elsewhere in the repo. */
export const syncedPages = [];

/**
 * Top-level docs navigation entries in sidebar order.
 *
 * @type {Array<
 *   | { kind: 'overview'; title: string }
 *   | { kind: 'page'; slug: string; title: string; maxDepth?: number; pinnedBottom?: true }
 *   | { kind: 'group'; slug: string; title: string; pages: SyncedDocPage[] }
 * >}
 */
export const docsNav = [
  { kind: 'overview', title: 'Home' },
  { kind: 'page', slug: 'features', title: 'Features', maxDepth: 2 },
  { kind: 'page', slug: 'getting-started', title: 'Getting started', maxDepth: 2 },
  { kind: 'page', slug: 'settings', title: 'Settings', maxDepth: 2 },
  { kind: 'page', slug: 'collections', title: 'Collections', maxDepth: 2 },
  { kind: 'page', slug: 'requests', title: 'Making requests', maxDepth: 2 },
  { kind: 'page', slug: 'request-scripts', title: 'Request scripts', maxDepth: 2 },
  { kind: 'page', slug: 'environments', title: 'Environments', maxDepth: 2 },
  
];

/** Slugs of canonical overview pages committed under docs/<slug>/index.md. */
export const groupOverviewSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'group').map((entry) => entry.slug),
);

/** Slugs of canonical guide pages committed as docs/<slug>.md. */
export const canonicalPageSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'page').map((entry) => entry.slug),
);
