import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DYNAMIC_VARIABLE_CATEGORIES,
  DYNAMIC_VARIABLES
} from '../src/shared/dynamicVariables.ts';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoDir = path.resolve(scriptDir, '..');
const outputPath = path.join(repoDir, 'docs/variables.md');

/**
 * Escapes pipe characters for markdown table cells.
 *
 * @param value - Raw cell text.
 */
function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/**
 * Builds the Variables reference page from the shared dynamic-variable registry.
 */
function buildVariablesDoc(): string {
  const sections = DYNAMIC_VARIABLE_CATEGORIES.map((category) => {
    const rows = category.keys
      .map((key) => {
        const description = DYNAMIC_VARIABLES[key]?.description ?? '';
        return `| \`{{${key}}}\` | ${escapeTableCell(description)} |`;
      })
      .join('\n');

    return `## ${category.title}

| Variable | Description |
| --- | --- |
${rows}`;
  }).join('\n\n');

  return `<!-- Generated by scripts/generate-variables-doc.ts. Do not edit manually. -->

# Variables

HarborClient supports **dynamic variables** — Postman-compatible placeholders whose values are generated fresh each time a request is sent. Use them in \`{{$name}}\` syntax in:

- Request URLs
- Headers and query params
- Request body
- Auth fields

Dynamic variable names are **case-sensitive** and include the leading \`$\`. Each placeholder resolves to a new value on every send. The set is backed by [\`@faker-js/faker\`](https://fakerjs.dev/) for randomized sample data.

## Static vs dynamic variables

**Collection and environment variables** use \`{{key}}\` syntax without a \`$\` prefix. You define the key and value yourself in collection or environment settings.

**Dynamic variables** use \`{{$name}}\` syntax. HarborClient generates the value at send time — you do not store it in a variable table.

Static variables take precedence. If you define a collection or environment variable with the same key as a dynamic variable (for example \`$randomInt\`), the static value is used instead. See [Environments](/environments) for merge order and precedence.

## Using dynamic variables in scripts

In pre- and post-request scripts, use \`hc.variables.replaceIn()\` to resolve placeholders in a string. See [Request scripts](/request-scripts) for the full \`hc.variables\` API.

\`\`\`javascript
hc.request.url = hc.variables.replaceIn('https://api.example.com/users/{{$guid}}');
console.log(hc.variables.replaceIn('Email: {{$randomEmail}}'));
\`\`\`

## Dynamic variable reference

${sections}

## Notes

- Values are generated when the request runs, not when you type the placeholder.
- Unknown \`{{$name}}\` tokens that are not in this list are left unchanged in the outgoing request.
- Image URL variables return placeholder image URLs suitable for mock requests.
`;
}

const markdown = buildVariablesDoc();
await writeFile(outputPath, markdown, 'utf8');

const variableCount = DYNAMIC_VARIABLE_CATEGORIES.reduce(
  (total, category) => total + category.keys.length,
  0
);

console.log(
  `Wrote ${path.relative(repoDir, outputPath)} with ${variableCount} dynamic variable(s) in ${DYNAMIC_VARIABLE_CATEGORIES.length} categories`
);
